mongodb:
  image: library/mongo
  ports:
    - "27017:27017"
rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  environment:
    - cluster.name=es-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    - "discovery.type=single-node"
  ulimits:
    memlock:
      soft: -1
      hard: -1
  ports:
    - "9200:9200"
    - "9300:9300"

